export const rolePermissions = [
  { name: "Administrator", value: BigInt(1 << 3) },
  { name: "View Audit Log", value: BigInt(1 << 7) },
  { name: "Manage Server", value: BigInt(1 << 5) },
  { name: "Manage Roles", value: BigInt(1 << 28) },
  { name: "Manage Channels", value: BigInt(1 << 4) },
  { name: "Kick Members", value: BigInt(1 << 1) },
  { name: "Ban Members", value: BigInt(1 << 2) },
  { name: "Create Instant Invite", value: BigInt(1 << 0) },
  { name: "Change Nickname", value: BigInt(1 << 26) },
  { name: "Manage Nicknames", value: BigInt(1 << 27) },
  { name: "Manage Emojis and Stickers", value: BigInt(1 << 30) },
  { name: "Manage Webhooks", value: BigInt(1 << 29) },
  { name: "View Channels", value: BigInt(1 << 10) },
  { name: "Manage Events", value: BigInt(1 << 33) },
  { name: "Moderate Members", value: BigInt(1 << 40) },
];

export const textChannelPermissions = [
  { name: "View Channel", value: BigInt(1 << 10) },
  { name: "Manage Channel", value: BigInt(1 << 4) },
  { name: "Manage Permissions", value: BigInt(1 << 28) },
  { name: "Manage Webhooks", value: BigInt(1 << 29) },
  { name: "Create Instant Invite", value: BigInt(1 << 0) },
  { name: "Send Messages", value: BigInt(1 << 11) },
  { name: "Send Messages in Threads", value: BigInt(1 << 38) },
  { name: "Create Public Threads", value: BigInt(1 << 35) },
  { name: "Create Private Threads", value: BigInt(1 << 36) },
  { name: "Embed Links", value: BigInt(1 << 14) },
  { name: "Attach Files", value: BigInt(1 << 15) },
  { name: "Add Reactions", value: BigInt(1 << 6) },
  { name: "Use External Emojis", value: BigInt(1 << 18) },
  { name: "Use External Stickers", value: BigInt(1 << 37) },
  { name: "Mention Everyone", value: BigInt(1 << 17) },
  { name: "Manage Messages", value: BigInt(1 << 13) },
  { name: "Manage Threads", value: BigInt(1 << 34) },
  { name: "Read Message History", value: BigInt(1 << 16) },
  { name: "Send TTS Messages", value: BigInt(1 << 12) },
  { name: "Use Application Commands", value: BigInt(1 << 31) },
];

export const voiceChannelPermissions = [
  { name: "View Channel", value: BigInt(1 << 10) },
  { name: "Manage Channel", value: BigInt(1 << 4) },
  { name: "Manage Permissions", value: BigInt(1 << 28) },
  { name: "Create Instant Invite", value: BigInt(1 << 0) },
  { name: "Connect", value: BigInt(1 << 20) },
  { name: "Speak", value: BigInt(1 << 21) },
  { name: "Stream", value: BigInt(1 << 9) },
  { name: "Use Activities", value: BigInt(1 << 39) },
  { name: "Use VAD", value: BigInt(1 << 25) },
  { name: "Priority Speaker", value: BigInt(1 << 8) },
  { name: "Mute Members", value: BigInt(1 << 22) },
  { name: "Deafen Members", value: BigInt(1 << 23) },
  { name: "Move Members", value: BigInt(1 << 24) },
];

